//confronti
alert( 3 > 2 ); // true (il risultato è giusto)
alert( 3 == 2 ); //false (il risultato è sbagliato)
alert(3 != 2 ); // true (il risultato è giusto)


//assegnazione del risultato ad una variabile
let result = 3 > 2;
alert( result ); //true (corretto)


//confronto di stringhe
alert('Y' > 'B' ); //true (corretto)
alert('Blot' > 'Blet'); // true (corretto)
alert('Gee' > 'Ge'); //true (corretto)       


//confronti tra tipi differenti
alert( '3' > 2 ); //true ('3' viene convertito in 3)
alert( '02' == 2 ); // true ('02' diventa 2)
